program: main_CIFAR.py
method: random
name: CIFAR10 - compare with previous local receptive results(0.03 lr, 100 epochs, [3072,3072,3072])
description:
  To overfit on 11*11 local receptive field.
run_cap: 10
metric:
  goal: minimize
  name: test error
parameters:
  lr:
    min: 0.06
    max: 0.1
  threshold:
    value: 2.0
  num_epochs:
    values: [1000, 2000]  # 4000 is too big and will cause Cuda-out-of-memory.
  weight_decay:
    value: 0.01
  batch_size:
    value: 5000
  dims:
    value: [3072, 3072, 3072, 3072, 10]
  receptive_size:
    value: 11
  # dropout:
  #   value: 0.5
