program: main_CIFAR.py
method: random
name: CIFAR10 - local receptive - size 11*11(2000 epochs, 0.08-0.15 lr, 2500 batch size)
description:
  To overfit on 11*11 local receptive field.
run_cap: 10
metric:
  goal: minimize
  name: test error
parameters:
  lr:
    min: 0.08
    max: 0.15
  threshold:
    value: 2.0
  num_epochs:
    value: 2000  # 4000 is too big and will cause Cuda-out-of-memory.
  weight_decay:
    value: 0.01
  dropout:
    value: 0.0
  batch_size:
    value: 2500
  dims:
    value: [3072, 3072, 3072, 3072]
