program: main_CIFAR.py
method: random
name: CIFAR10 - modified pipeline - to overfit
description:
  modify training pipeline, train layer by layer with no "global epoch".
run_cap: 10
metric:
  goal: minimize
  name: test error
parameters:
  lr:
    value: 0.03
  threshold:
    value: 2.0
  num_epochs:
    value: 500
  weight_decay:
    value: 0.01
  dropout:
    value: 0.5
  batch_size:
    value: 5000
  dims:
    value: [3072, 3072, 3072, 1536]
