program: main_CIFAR.py
method: random
name: CIFAR10 - local receptive - size 21*21(mid lr, more epochs)
description:
  To overfit on the implementation of local receptive field really works by increasing num_epochs
run_cap: 10
metric:
  goal: minimize
  name: test error
parameters:
  lr:
    min: 0.1
    max: 0.2
  threshold:
    value: 2.0
  num_epochs:
    values: [2000, 3000]
  weight_decay:
    value: 0.01
  dropout:
    value: 0.0
  batch_size:
    value: 5000
  dims:
    values: [[3072, 3072, 3072], [3072, 3072, 3072, 3072]]
