program: main_MNIST.py
method: random
name: MNIST - modified pipeline
metric:
  goal: minimize
  name: test_error
parameters:
  lr:
    value: 0.03
  threshold:
    value: 2.0
  num_epochs:
    value: 100
  batch_size:
    value: 5000
  dims:
    value: [784, 1000, 1000]